In [ ]:
import numpy as np
from multiprocessing import Queue

In [ ]:
a = Queue()

In [ ]:
b= np.array([2,3,4])
b

In [7]:
a.put(b)
a.put(3)

In [11]:
for i in a:
    print(a.get())

TypeError: 'Queue' object is not iterable

In [8]:
c=a.get()

In [9]:
c

array([2, 3, 4])

In [10]:
d=a.get()
d

3

In [14]:
q=np.array([2,3,4,5,6,7])
new_value=8
t=q.min()
print t

2


In [15]:
q[np.where(q.min())] = new_value
print(q)

[8 3 4 5 6 7]


In [16]:
q.sort()

In [17]:
q

array([3, 4, 5, 6, 7, 8])

In [18]:
f=lambda x: x*2
rate=0
for i in q:
    rate+=i

In [19]:
rate

33

In [20]:
q.max()-3

5

In [21]:
z=np.zeros((4,))

In [22]:
w=z.min()

In [23]:
w

0.0

In [24]:
z[np.where(z.min())]=4

In [25]:
z

array([ 0.,  0.,  0.,  0.])

In [26]:
u=np.array([1,4,5,1])

In [27]:
u

array([1, 4, 5, 1])

In [28]:
u[np.where(u.min())]=4

In [29]:
u

array([4, 4, 5, 1])

In [36]:
pop_last = np.array([[1,2],[5,6]])
pop_last

array([[1, 2],
       [5, 6]])

In [37]:
print(pop_last[1])

[5 6]


In [38]:
pop_last[1]=[7,8]

In [39]:
pop_last

array([[1, 2],
       [7, 8]])